
	CREATE TABLE  oms_refund_info (
		refund_id BIGINT(20)  not null AUTO_INCREMENT comment '退款编号' ,
		order_id BIGINT(20)  not null  comment '订单编号' ,
		down_channel_no VARCHAR(32)  not null  comment '下游渠道编号' ,
		request_no VARCHAR(32)  not null  comment '下游渠道订单号' ,
		down_refund_no VARCHAR(32)  not null  comment '下游退款编号' ,
		down_shelf_id BIGINT(10)  not null  comment '下游货架编号' ,
		down_product_id BIGINT(10)  not null  comment '下游商品编号' ,
		ext_product_no VARCHAR(32)    comment '外部商品编号' ,
		line_id BIGINT(10)  not null  comment '产品线' ,
		carrier_no VARCHAR(8)  not null  comment '运营商' ,
		province_no VARCHAR(8)  not null  comment '省份' ,
		city_no VARCHAR(8)  not null  comment '城市' ,
		refund_type TINYINT(1)  not null  comment '退款方式（1.普通退款，2.强制退款，3.人工退款）' ,
		face DECIMAL(20,5)  not null  comment '商品面值' ,
		refund_num BIGINT(10)  not null  comment '退款商品数量' ,
		refund_face DECIMAL(20,5)  not null  comment '退款商品总面值' ,
		refund_mer_amount DECIMAL(20,5) default 0 not null  comment '+退款用户支付金额' ,
		refund_courier_amount DECIMAL(20,5) default 0 not null  comment '+退款快递金额' ,
		refund_sell_amount DECIMAL(20,5)  not null  comment '退款总销售金额' ,
		refund_commission_amount DECIMAL(20,5)  not null  comment '退款总佣金金额' ,
		refund_service_amount DECIMAL(20,5)  not null  comment '退款总服务费金额' ,
		refund_fee_amount DECIMAL(20,5)  not null  comment '退款总手续费金额' ,
		create_time DATETIME default current_timestamp not null  comment '创建时间' ,
		refund_status SMALLINT(3) default 10 not null  comment '状态（10.退货，20.退款,0成功，90失败）' ,
		up_return_status SMALLINT(3) default 20 not null  comment '上游退货状态（0.退货成功，20.等待退货，30.正在退货，90.退款失败，91.部分退款）' ,
		down_refund_status SMALLINT(3) default 10 not null  comment '下游退款状态（0成功，10.未开始，20.等待，30正在，99无需）' ,
		refund_notify_status SMALLINT(3) default 10 not null  comment '退款告知状态（0成功，100查询成功，10.未开始，20.等待，30正在，99.无需）' ,
		return_overtime DATETIME  not null  comment '退货超时时间' ,
		complete_up_refund TINYINT(1) default 1 not null  comment '是否全部完成上游退货（1.未完成，0.已完成）' ,
		extend_info LONGTEXT    comment '+扩展信息' ,
		PRIMARY KEY (refund_id),
		UNIQUE KEY UNQ_MER_REFUND (down_channel_no,down_refund_no),
		
		KEY key_oms_refund_info_order_id (order_id),
		KEY key_oms_refund_info_create_time (create_time)
		) ENGINE=InnoDB AUTO_INCREMENT=20000 DEFAULT CHARSET=utf8 COMMENT='退款记录'
