
	CREATE TABLE  oms_order_info (
		order_id BIGINT(20)  not null AUTO_INCREMENT comment '订单编号' ,
		down_channel_no VARCHAR(32)  not null  comment '下游渠道编号' ,
		request_no VARCHAR(32)  not null  comment '下游渠道订单编号' ,
		down_shelf_id BIGINT(10)  not null  comment '下游货架编号' ,
		down_product_id BIGINT(10)  not null  comment '下游商品编号' ,
		ext_product_no VARCHAR(32)    comment '外部商品编号' ,
		line_id BIGINT(10)  not null  comment '产品线' ,
		carrier_no VARCHAR(8)  not null  comment '运营商' ,
		province_no VARCHAR(8)  not null  comment '省份' ,
		city_no VARCHAR(8)  not null  comment '城市' ,
		invoice_type SMALLINT(3)  not null  comment '开票方式（1.不开发票，0.不限制，2.需要发票）' ,
		face DECIMAL(20,5)  not null  comment '商品面值' ,
		num BIGINT(10)  not null  comment '商品数量' ,
		total_face DECIMAL(20,5)  not null  comment '商品总面值' ,
		mer_amount DECIMAL(20,5) default 0 not null  comment '+用户支付金额' ,
		courier_amount DECIMAL(20,5) default 0 not null  comment '+支付快递金额' ,
		sell_amount DECIMAL(20,5)  not null  comment '总销售金额' ,
		commission_amount DECIMAL(20,5)  not null  comment '总佣金金额' ,
		service_amount DECIMAL(20,5)  not null  comment '总服务费金额' ,
		fee_amount DECIMAL(20,5)  not null  comment '总手续费金额' ,
		can_split_order TINYINT(1)  not null  comment '是否拆单' ,
		split_order_face DECIMAL(20,5)  not null  comment '拆单面值' ,
		create_time DATETIME default current_timestamp not null  comment '创建时间' ,
		order_overtime DATETIME  not null  comment '订单超时时间' ,
		delivery_pause TINYINT(1) default 1 not null  comment '发货暂停（0.是，1否）' ,
		order_status SMALLINT(3) default 10 not null  comment '订单状态（10.支付，20.绑定发货，0.成功，90.失败，91.部分成功）' ,
		payment_status SMALLINT(3) default 20 not null  comment '支付状态（0支付成功，10.未开始，20.等待支付，30.正在支付，90.支付超时）' ,
		delivery_bind_status SMALLINT(3) default 10 not null  comment '发货绑定状态（0发货成功，10.未开始，20.等待绑定，30.正在发货，90.全部失败）' ,
		refund_status SMALLINT(3) default 10 not null  comment '订单失败退款状态（0退款成功，10.未开始，20.等待退款，30.正在退款，99.无需退款）' ,
		notify_status SMALLINT(3) default 10 not null  comment '订单信息告知状态（0通知成功，100查询成功，10.未开始，20.等待告知，30.正在告知）' ,
		complete_up_pay TINYINT(1) default 1 not null  comment '完成上游支付（0.是，1否）' ,
		is_refund TINYINT(1) default 1 not null  comment '用户退款（0.是，1否）' ,
		bind_face DECIMAL(20,5) default 0 not null  comment '成功绑定总面值' ,
		success_face DECIMAL(20,5) default 0 not null  comment '实际成功总面值' ,
		success_sell_amount DECIMAL(20,5) default 0 not null  comment '实际成功总销售金额 （1）' ,
		success_commission DECIMAL(20,5) default 0 not null  comment '实际成功总佣金金额 （2）' ,
		success_service DECIMAL(20,5) default 0 not null  comment '实际成功总服务费金额 （3）' ,
		success_fee DECIMAL(20,5) default 0 not null  comment '实际成功总手续费金额 （4）' ,
		success_cost_amount DECIMAL(20,5) default 0 not null  comment '实际发货成功总成本  （5）' ,
		success_up_commission DECIMAL(20,5) default 0 not null  comment '实际发货成功总上游佣金 （6）' ,
		success_up_service DECIMAL(20,5) default 0 not null  comment '实际发货成功总上游服务费 （7）' ,
		profit DECIMAL(20,5) default 0 not null  comment '利润（1-2+3-4-5+6+7）' ,
		rechage_account VARCHAR(32)    comment '充值账户' ,
		extend_info LONGTEXT    comment '扩展信息' ,
		PRIMARY KEY (order_id),
		UNIQUE KEY UNQ_MER_ORDER (down_channel_no,request_no),
		
		KEY key_oms_order_info_create_time (create_time)
		) ENGINE=InnoDB AUTO_INCREMENT=1100000000 DEFAULT CHARSET=utf8 COMMENT='订单记录'
