
	CREATE TABLE  oms_refund_up_return (
		return_id BIGINT(20)  not null AUTO_INCREMENT comment '退货编号' ,
		up_channel_no VARCHAR(32)  not null  comment '上游渠道编号' ,
		up_product_id BIGINT(10)  not null  comment '上游商品编号' ,
		up_return_no VARCHAR(32)    comment '上游退货编号' ,
		up_ext_product_no VARCHAR(32)    comment '上游商品请求编号' ,
		order_id BIGINT(20)  not null  comment '订单编号' ,
		refund_id BIGINT(20)  not null  comment '退款编号' ,
		delivery_id BIGINT(20)  not null  comment '发货编号' ,
		down_channel_no VARCHAR(32)  not null  comment '下游渠道编号' ,
		down_product_id BIGINT(10)  not null  comment '下游商品编号' ,
		line_id BIGINT(10)  not null  comment '产品线' ,
		carrier_no VARCHAR(8)  not null  comment '运营商' ,
		province_no VARCHAR(8)  not null  comment '省份' ,
		city_no VARCHAR(8)  not null  comment '城市' ,
		return_status SMALLINT(3) default 20 not null  comment '退货状态（0.退货成功，20等待退货，30正在退货，90退货失败）' ,
		up_refund_status SMALLINT(3) default 10 not null  comment '退款状态（0退款成功，10.未开始，20.等待退款，30.正在退款，99无需退款）' ,
		create_time DATETIME default current_timestamp not null  comment '创建时间' ,
		return_face DECIMAL(20,5)  not null  comment '商品面值' ,
		return_num BIGINT(10)  not null  comment '退货数量' ,
		return_total_face DECIMAL(20,5)  not null  comment '退货总面值' ,
		return_cost_amount DECIMAL(20,5)  not null  comment '退回成本' ,
		return_commission_amount DECIMAL(20,5)  not null  comment '退回佣金' ,
		return_service_amount DECIMAL(20,5)  not null  comment '退回服务费' ,
		courier_refund_amount DECIMAL(20,5) default 0   comment '+退回快递费' ,
		start_time DATETIME    comment '开始时间' ,
		end_time DATETIME    comment '结束时间' ,
		return_msg VARCHAR(256)    comment '退货返回信息' ,
		extend_info LONGTEXT    comment '+扩展信息' ,
		PRIMARY KEY (return_id),
		KEY key_oms_refund_up_return_order_id (order_id),
		KEY key_oms_refund_up_return_create_time (create_time)
		) ENGINE=InnoDB AUTO_INCREMENT=20000 DEFAULT CHARSET=utf8 COMMENT='上游退货信息表'
