
	CREATE TABLE  oms_order_delivery (
		delivery_id BIGINT(20)  not null AUTO_INCREMENT comment '发货编号' ,
		up_channel_no VARCHAR(32)  not null  comment '上游渠道编号' ,
		up_product_id BIGINT(10)  not null  comment '上游商品编号' ,
		up_delivery_no VARCHAR(32)    comment '上游发货编号' ,
		up_ext_product_no VARCHAR(32)    comment '上游商品请求编号' ,
		order_id BIGINT(20)  not null  comment '订单编号' ,
		down_channel_no VARCHAR(32)  not null  comment '下游渠道编号' ,
		down_product_id BIGINT(10)  not null  comment '下游商品编号' ,
		line_id BIGINT(10)  not null  comment '产品线' ,
		carrier_no VARCHAR(8)  not null  comment '运营商' ,
		province_no VARCHAR(8)  not null  comment '省份' ,
		city_no VARCHAR(8)  not null  comment '城市' ,
		invoice_type SMALLINT(3)  not null  comment '开票方式（1.不开发票，2.上游开发票）' ,
		delivery_status SMALLINT(3) default 20 not null  comment '发货状态（0.发货成功，20等待发货，30正在发货，90发货失败）' ,
		up_payment_status SMALLINT(3) default 10 not null  comment '上游支付状态（0支付成功，10未开始,20.等待支付，30.正在支付，99.无需支付）' ,
		create_time DATETIME default current_timestamp not null  comment '创建时间' ,
		face DECIMAL(20,5)  not null  comment '商品面值' ,
		num BIGINT(10)  not null  comment '发货数量' ,
		total_face DECIMAL(20,5)  not null  comment '发货总面值' ,
		cost_amount DECIMAL(20,5)  not null  comment '发货成本' ,
		up_commission_amount DECIMAL(20,5)  not null  comment '上游佣金' ,
		service_amount DECIMAL(20,5)  not null  comment '发货服务费' ,
		courier_cost_amount DECIMAL(20,5) default 0   comment '+快递费' ,
		start_time DATETIME    comment '开始时间' ,
		end_time DATETIME    comment '结束时间' ,
		return_msg VARCHAR(256)    comment '发货返回信息' ,
		extend_info LONGTEXT    comment '+扩展信息' ,
		PRIMARY KEY (delivery_id),
		KEY key_oms_order_delivery_order_id (order_id),
		KEY key_oms_order_delivery_create_time (create_time)
		) ENGINE=InnoDB AUTO_INCREMENT=20000 DEFAULT CHARSET=utf8 COMMENT='订单发货表'
